In [1]:
import pandas as pd

In [2]:
data=pd.read_csv('dtt.csv')

C:\Users\FerCX\AppData\Local\Temp\ipykernel_10104\1363515088.py:1: DtypeWarning: Columns (1,8,15,17,23,25,27,34,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216,217,218,219,220,221,222,223,224,225,226,227,228,229,232,233,234,235,236,237,238,239,240,241,242,243,244,245,246,247,248,249,250,251,252,253,254,255,256,257,258,259,260,261,264,265,266,267,268,269,270,271,272,273,274,275,276,277,278,279,280,281,282,283,284,285,286,287,288,289,290,291,292,293,296,297,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,318,319,320,321,322,323,324,325,329,333,340,349,356,357,358,359,360,361,362,363,364,365,366,367,368,369,370,371,372,373,374,375,376,377,378,379,380,381,382,383,384,385,388,389,390,391,392,393,394,395,396,397,398,399,400,401,402,403,404,405,406,407,408,409,410,411,412,413,414,415,416,417,420,421,422,423,424,425,426,427,428,429,430,431,432,433,434,435,436,437,438,439,440,441,442,443,444,445,446,447,448,449,452,453,454,455,456,457,458,459,460,461,462,463,464,465,466,467,468,469,470,471,472,473,474,475,476,477,478,479,480,481,484,491,493,499,501,503,510,516,517,518,519,520,521,522,523,524,525,526,527,528,529,530,531,532,533,534,535,536,537,538,539,540,541,542,543,544,545,548,549,550,551,552,553,554,555,556,557,558,559,560,561,562,563,564,565,566,567,568,569,570,571,572,573,574,575,576,577,580,581,582,583,584,585,586,587,588,589,590,591,592,593,594,595,596,597,598,599,600,601,602,603,604,605,606,607,608,609,612,613,614,615,616,617,618,619,620,621,622,623,624,625,626,627,628,629,630,631,632,633,634,635,636,637,638,639,640,641,644,645,646,647,648,649,650,651,652,653,654,655,656,657,658,659,660,661,662,663,664,665,666,667,668,669,670,671,672,673,677,681,688) have mixed types. Specify dtype option on import or set low_memory=False.
  data=pd.read_csv('dtt.csv')

In [3]:
data

,[[1.0,1.0,63.0,57.0,52.0,59.0,68.0],[2.0,3.0,47.0,...,1.6,0.9,36,0.10,57,0.11,70,0.12,0]].1,1.7
0,[[1.0,1.0,63.0,63.0,71.0,61.0,66.0],[2.0,3.0,51.0,...,1,0,51,0,50,0,57,1,0]],2
1,[[1.0,1.0,67.0,67.0,73.0,65.0,70.0],[2.0,3.0,57.0,...,0,0,44,0,58,0,37,1,0]],1
2,[[1.0,1.0,63.0,57.0,52.0,59.0,68.0],[2.0,3.0,47.0,...,1,0,53,0,50,0,61,1,0]],1
3,[[1.0,1.0,69.0,66.0,61.0,63.0,71.0],[2.0,3.0,53.0,...,1,0,65,0,70,1,70,0,0]],0
4,[[1.0,1.0,72.0,70.0,69.0,70.0,74.0],[2.0,3.0,21.0,...,0,0,44,0,58,0,37,1,0]],1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14472,[[1.0,1.0,63.0,49.0,53.0,50.0,60.0],[2.0,3.0,53.0,...,1,0,57,0,56,0,49,1,0]],0
14473,[[1.0,1.0,72.0,59.0,66.0,66.0,70.0],[2.0,3.0,48.0,...,0,0,59,0,34,0,64,1,0]],2
14474,[[1.0,1.0,69.0,56.0,73.0,66.0,67.0],[2.0,3.0,68.0,...,1,Free Form,50,0,60,0,58,1,0]],2
14475,[[1.0,1.0,71.0,68.0,65.0,68.0,72.0],[2.0,3.0,64.0,...,1,0,52,0,47,0,50,1,0]],2
14476,[[1.0,1.0,58.0,66.0,62.0,52.0,62.0],[2.0,3.0,58.0,...,1,0,29,1,35,0,38,1,0]],0